version: '3.4'

services:

    catalog.webapi:
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_HTTP_PORTS=8080
            - ASPNETCORE_HTTPS_PORTS=8081
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx 
            - ASPNETCORE_Kestrel__Certificates__Default__Password=123456 
        ports:
            - "8080:8080"
            - "8081:8081"
            - "5000:5000"
            - "5001:5001"
        volumes:
            - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
            - ~/.aspnet/https:/https:ro

    bom_negocio.db:
        environment:
            POSTGRES_DB: catalog
            POSTGRES_USER: catalog
            POSTGRES_PASSWORD: catalog123
        ports:
            - "5432:5432"
            - "5433:5433"
        volumes:
            - bom_negocio.db_data:/var/lib/postgresql/data
#            - ./*.sh:/docker-entrypoint-initdb.d/

    auth.webapi:
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_HTTP_PORTS=8080
            - ASPNETCORE_HTTPS_PORTS=8081
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
            - ASPNETCORE_Kestrel__Certificates__Default__Password=123456 
        ports:
            - "8085:8080"
            - "8086:8081"
        volumes:
            - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
            - ~/.aspnet/https:/https:ro

volumes:
  bom_negocio.db_data:

