version: '3.4'

services:

    catalog.webapi:
        image: ${DOCKER_REGISTRY-}catalogwebapi
        hostname: catalog
        container_name: catalog
        depends_on:
            - bom_negocio.db
        build:
            context: .
            dockerfile: Catalog.WebApi/Dockerfile
        profiles: ["vs_debug"]

    bom_negocio.db:
        image: postgres:16.4
        hostname: bom_negocio_db
        container_name: bn_db
        profiles: ["vs_debug", "vs_sso_debug"]


    auth.webapi:
        image: ${DOCKER_REGISTRY-}authwebapi
        hostname: auth
        container_name: auth
        build:
            context: .
            dockerfile: Auth.WebApi/Dockerfile
        depends_on:
            - bom_negocio.db
        profiles: ["vs_debug", "vs_sso_debug"]


    getway.webapi:
        image: ${DOCKER_REGISTRY-}getwaywebapi
        hostname: getway
        container_name: getway
        build:
            context: .
            dockerfile: Getway.WebApi/Dockerfile
        depends_on:
            # - catalog.webapi
            - auth.webapi
            - bom_negocio.db
        profiles: ["vs_sso_debug"]

    aux:
        image: alpine:3.14
        command: sh -c "apk add --no-cache curl && while true; do sleep 30; done"
        hostname: aux
        container_name: aux
        stdin_open: true
        tty: true
        profiles: ["vs_sso_debug"]
