#See https://aka.ms/overrideVSDockerComposeConfiguration to understand how Visual Studio uses this override file.
# refs: https://docs.docker.com/compose/extends/
# https://docs.docker.com/compose/compose-file/compose-file-v3/
# https://docs.docker.com/guides/dotnet/develop/

version: '3.4'

services:

    auth.webapi:
        labels:
            com.microsoft.visualstudio.debuggee.program: "dotnet"
            com.microsoft.visualstudio.debuggee.arguments: "\"/app/bin/Debug/net8.0/Auth.WebApi.dll\""
            com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
            com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""

    getway.webapi:
        labels:
            com.microsoft.visualstudio.debuggee.program: "dotnet"
            com.microsoft.visualstudio.debuggee.arguments: "\"/app/bin/Debug/net8.0/Getway.WebApi.dll\""
            com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
            com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""

    cart.webapi:
        labels:
            com.microsoft.visualstudio.debuggee.program: "dotnet"
            com.microsoft.visualstudio.debuggee.arguments: "\"/app/bin/Debug/net8.0/Cart.WebApi.dll\""
            com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
            com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
  
    order.webapi:
        labels:
            com.microsoft.visualstudio.debuggee.program: "dotnet"
            com.microsoft.visualstudio.debuggee.arguments: "\"/app/bin/Debug/net8.0/Order.WebApi.dll\""
            com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
            com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""

    catalog.api:
        labels:
            com.microsoft.visualstudio.debuggee.program: "dotnet"
            com.microsoft.visualstudio.debuggee.arguments: "\"/app/bin/Debug/net8.0/Catalog.Api.dll\""
            com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
            com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
            #com.microsoft.visual-studio.project-name: "Catalog.Api"