#See https://aka.ms/overrideVSDockerComposeConfiguration to understand how Visual Studio uses this override file.
# refs: https://docs.docker.com/compose/extends/
# https://docs.docker.com/compose/compose-file/compose-file-v3/
# https://docs.docker.com/guides/dotnet/develop/

version: '3.4'

#services:
  #catalog.webapi:
    #labels:
      #com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: "\"/app/Catalog.WebApi.dll\""
      #com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      #com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
      #com.microsoft.visual-studio.project-name: "Catalog.WebApi"