use catalogDb;

-- https://www.npgsql.org/efcore/modeling/generated-properties.html?tabs=13%2Cefcore5#identity-and-serial-columns-auto-increment

CREATE TABLE IF NOT EXISTS categoria(
  id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  nome VARCHAR(100) NOT NULL,
  descricao VARCHAR(500) DEFAULT NULL,
  categoria_pai INTEGER DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT FK_categoria_categoriaPai FOREIGN KEY (categoria_pai) REFERENCES categoria(id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT CHK_categoria_categoriaPai CHECK (categoria_pai <> id)
);

CREATE TABLE IF NOT EXISTS produto(
  id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  nome VARCHAR(100) NOT NULL,
  descricao VARCHAR(500) NOT NULL,
  sku VARCHAR(20) UNIQUE NOT NULL,
  preco DECIMAL(10,2) NOT NULL,
  quantidade INTEGER NOT NULL,
  categoria_id INTEGER NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT FK_produto_categoria FOREIGN KEY (categoria_id) REFERENCES categoria(id) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS imagem(
  id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  path_url VARCHAR(20) NOT NULL,
  produto_id INTEGER NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT FK_imagem_produto FOREIGN KEY (produto_id) REFERENCES produto(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS IDX_produto_categoria ON produto(categoria_id);

INSERT INTO categoria(nome, descricao, categoria_pai) VALUES('Vestuário', 'Categoria de roupas e acessórios em geral', NULL);
INSERT INTO categoria(nome, descricao, categoria_pai) VALUES('Eletrônicos', 'Categoria de produtos eletrônicos', NULL);
INSERT INTO categoria(nome, descricao, categoria_pai) VALUES('Calçados', 'Categoria de calçados', 2);
INSERT INTO categoria(nome, descricao, categoria_pai) VALUES('Roupas', 'Categoria de roupas', 2);
INSERT INTO categoria(nome, descricao, categoria_pai) VALUES('Smartphones', 'Categoria de smartphones', 1);
INSERT INTO categoria(nome, descricao, categoria_pai) VALUES('Notebooks', 'Categoria de notebooks', 1);
INSERT INTO categoria(nome, descricao, categoria_pai) VALUES('Televisores', 'Categoria de televisores', 1);
INSERT INTO categoria(nome, descricao, categoria_pai) VALUES('Informática', 'Categoria de produtos de informática', NULL);
INSERT INTO categoria(nome, descricao, categoria_pai) VALUES('Periféricos', 'Categoria de periféricos', 5);
INSERT INTO categoria(nome, descricao, categoria_pai) VALUES('Hardware', 'Categoria de hardware', 5);
INSERT INTO categoria(nome, descricao, categoria_pai) VALUES('Software', 'Categoria de software', 5);
INSERT INTO categoria(nome, descricao, categoria_pai) VALUES('Acessórios', 'Categoria de acessórios', 5);
INSERT INTO categoria(nome, descricao, categoria_pai) VALUES('Móveis', 'Categoria de móveis', NULL);
INSERT INTO categoria(nome, descricao, categoria_pai) VALUES('Sala de estar', 'Categoria de móveis para sala de estar', 10);
INSERT INTO categoria(nome, descricao, categoria_pai) VALUES('Sala de jantar', 'Categoria de móveis para sala de jantar', 10);
INSERT INTO categoria(nome, descricao, categoria_pai) VALUES('Cozinha', 'Categoria de móveis para cozinha', 10);
INSERT INTO categoria(nome, descricao, categoria_pai) VALUES('Quarto', 'Categoria de móveis para quarto', 10);