global using Auth.WebApi.Models;
global using Auth.WebApi.Services.Implements;
global using Auth.WebApi.Services.Interfaces;
global using Auth.WebApi.Exceptions;
global using System.Net;
global using Auth.WebApi.DTO;
global using Auth.WebApi.Context;
global using Auth.WebApi.Middlewares;
global using Auth.WebApi.Extensions;